FROM python:3.7.6
USER root

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN apt-get install -y vim less
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install numpy==1.18.1
RUN pip install matplotlib==3.1.3
RUN pip install Mesa==0.8.7
RUN pip install Eel==0.14.0
RUN pip install seaborn==0.10.0